import json
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, TypedDict


class ConsolidationStrategy(TypedDict):
    canonical_key: str
    deprecated_keys: List[str]
    value: str
    reason: str


MigrationMap = Dict[str, str]


def choose_canonical_key(keys: List[str], usage_counts: Dict[str, int]) -> str:
    """
    Escolhe a chave canônica entre as chaves dadas.
    Regras (prioridade):
      1) Preferir chaves sem dígitos (mais genéricas), se existirem.
      2) Dentro do conjunto considerado, preferir a mais usada.
      3) Preferir chaves sem números (já feito), depois a mais curta.
      4) Ordem alfabética como último recurso.
    """
    if not keys:
        return ""
    if len(keys) == 1:
        return keys[0]

    # Primeiro, veja se há chaves sem números. Se houver, considere apenas essas.
    keys_without_digits = [k for k in keys if not re.search(r"\d", k)]
    candidate_keys = keys_without_digits if keys_without_digits else keys

    # Agora escolha a(s) mais usadas entre os candidatos
    sorted_by_usage = sorted(
        candidate_keys, key=lambda k: usage_counts.get(k, 0), reverse=True
    )
    max_usage = usage_counts.get(sorted_by_usage[0], 0)
    most_used = [k for k in sorted_by_usage if usage_counts.get(k, 0) == max_usage]
    if len(most_used) == 1:
        return most_used[0]

    # Se múltiplos com mesmo uso, preferir o mais curto
    by_length = sorted(most_used, key=len)
    min_len = len(by_length[0])
    shortest = [k for k in by_length if len(k) == min_len]
    if len(shortest) == 1:
        return shortest[0]

    # Ordem alfabética como fallback
    return sorted(shortest)[0]


def generate_consolidation_strategy(
    duplicate_value: str, keys: List[str], usage_counts: Dict[str, int]
) -> ConsolidationStrategy:
    canonical = choose_canonical_key(keys, usage_counts)
    deprecated = [k for k in keys if k != canonical]
    canonical_usage = usage_counts.get(canonical, 0)
    reason = f"Selected '{canonical}' as canonical key"
    if canonical_usage:
        reason += f" ({canonical_usage} usages in codebase)"
    if deprecated:
        deprecated_usages = sum(usage_counts.get(k, 0) for k in deprecated)
        reason += f". Will migrate {len(deprecated)} deprecated keys ({deprecated_usages} total usages)"
    return {
        "canonical_key": canonical,
        "deprecated_keys": deprecated,
        "value": duplicate_value,
        "reason": reason,
    }


def create_migration_map(strategies: List[ConsolidationStrategy]) -> MigrationMap:
    migration: MigrationMap = {}
    for s in strategies:
        for old in s["deprecated_keys"]:
            migration[old] = s["canonical_key"]
    return migration


def generate_migration_script(migration_map: MigrationMap) -> str:
    """
    Gera um script Python (string) que exporta o mapa de migração e fornece helpers.
    Inclui comentários com '#' para satisfazer os testes que procuram por comentários.
    """
    ts = datetime.utcnow().isoformat() + "Z"
    header = (
        f"# Auto-generated Migration Script\n"
        f"# Generated at: {ts}\n"
        f"# Generated by: Pessoa 3 - Gerador de Mapeamento (Python)\n\n"
        f'"""\nAuto-generated Migration Script\nGenerated at: {ts}\nGenerated by: Pessoa 3 - Gerador de Mapeamento (Python)\n"""\n\n'
    )
    body = "TRANSLATION_KEY_MIGRATION_MAP = {\n"
    for old, new in migration_map.items():
        body += f"    {json.dumps(old)}: {json.dumps(new)},\n"
    body += "}\n\n"
    helpers = """
def migrate_key(key: str) -> str:
    return TRANSLATION_KEY_MIGRATION_MAP.get(key, key)

def get_deprecated_keys() -> list:
    return list(TRANSLATION_KEY_MIGRATION_MAP.keys())

def is_deprecated_key(key: str) -> bool:
    return key in TRANSLATION_KEY_MIGRATION_MAP
"""
    return header + body + helpers


def export_strategies_to_json(
    strategies: List[ConsolidationStrategy],
    migration_map: MigrationMap,
    output_path: str,
) -> None:
    data = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "generated_by": "Pessoa 3 - Gerador de Mapeamento (Python)",
        "total_strategies": len(strategies),
        "total_migrations": len(migration_map),
        "strategies": strategies,
        "migration_map": migration_map,
    }
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
